#!/bin/bash

echo ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;"
echo "Syncing static files to s3 bucket"
echo ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;"

s3_buckets=()
if [ "$BITBUCKET_BRANCH" == "master" ]
then
    s3_buckets=(iepf-mis-static)
fi

for bucket in ${s3_buckets[*]}
do
    #aws s3 sync frontend/web/static/dist/pdf/ s3://$bucket/static/dist/pdf --quiet --delete --acl "public-read" --cache-control max-age=604800
     aws s3 sync frontend/web/static/dist/deploy/ s3://$bucket/static/dist/deploy --quiet --delete --acl "public-read" --cache-control max-age=604800
     aws s3 sync frontend/web/static/dist/fonts/ s3://$bucket/static/dist/fonts --quiet --delete --acl "public-read" --cache-control max-age=604800
     #aws s3 sync frontend/web/static/frontend/static/fonts/ s3://$bucket/static/frontend/static/fonts/ --quiet --delete --acl "public-read" --cache-control max-age=604800
     aws s3 sync frontend/web/static/dist/images/ s3://$bucket/static/dist/images --quiet --delete --acl "public-read" --cache-control max-age=604800
done
